{% set name = "lhcbdirac-config" %}

package:
  name: {{ name|lower }}
  version: "2020.05.27"

build:
  noarch: generic
  number: 0

requirements:
  run:
    - ca-policy-lcg

test:
  commands:
    - test -f "${CONDA_PREFIX}/etc/dirac.cfg"
    - echo "${X509_VOMS_DIR}"

about:
  home: https://lhcb-dirac.readthedocs.io/
  license: GPL-3.0-only
  license_file: LICENSE
  summary: 'Configuration package for LHCbDIRAC'

extra:
  recipe-maintainers:
    - chrisburr
