travis:
  secure:
    BINSTAR_TOKEN: huVWL1E15Y71H+UkNJ0c2LNeL6jVcx6v271E8fQvKZN685f83G059pmLrpMRJImKEmJFCdB9WdyVGEn+iNvQyALcS1wDy037Ysx2B7TYh2kxSA4cbaVcFKbXMlLV+Rm3dO2i0FiEH6EJU17zviOOj7+sW4VdyA1bsDfIuWDCidPgjs3cDOVsPuClDudqFe4HS1PUSV9W2fs88SVfX5NOjIIvkuS/6nIcVT4hMsfi50ZmsmhybldSMFr49B3/LQFKiC5fQEI4jW/UTkVwgx4Gd0ZQhGfOaTobRnS2gUk0iS6OUT+uHpJXVcLa0AfxV8t1x3FlpBwyBdOAgZ9iDTZvEVdN1G/QBU155+raJFLIsUnNSqhwx2E+R1ldB6Z+6wlZ55bZ+S+jZ2gXGlLaL+c6z+bciZa9DOaXbGnUyzRjAMhxx+fw41VNxkAFJhmINgaNzUrArMuHf/ZfJbZsqBgjp5Nz26LQjmAF8uVL3vekLfVLbZMXaoZSRwA8bQOpg7sGu8Dbr8h+nXW6hLFHqtywfpHFy+hLjG4hp8ZOKGzMUqb3b10GHY1I+DDbT11ye28bs3igI8y5PRGwWcj4aJjnz/jHXjeRBhSL3S/8nwN8B6y1ZMbudLmFiVvUsnaXNOdSo8V/Db4i2bnm7AYZFN6bVyf+mbXJm1uTgCK2kJAf6TI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
